### ISSUE TITLE
首页分类标签和本地图片获取的问题

### ISSUE THREAD

**Issue by JackChius** [zhangolve/hexo-theme-olive#1]
博主你好 
主题似乎不能正确显示本地图片，远程图片可以，格式要怎样写比较好？
分类标签那里 在主题yml配置文件设了几个分类，目前首页能显示分类，点开还是404 
还有可以从参考Next的配置教程吗，问题似乎有点多，说实话你的主题真挺好用的，文档写的比其他主题完善很多，希望这些问题解决了打算长期用下去哈

**Comment by JackChius** [comment]
headerpic: "img/15.jpg"
alipay: img/test.jpg
menu:
  Home: /
  Archives: /archives
  tags: /tags
  rss: /atom.xml
大概是这几个地方，现在首页图片可以，文章页还不能显示本地图片，首页的订阅我，关于我那些链接也还没能打开

**Comment by zhangolve** [comment]
左侧侧边栏显示的分类，必须已经写过这个分类的文章，否则就是404。因为你创建文章的时候，选择了分类，才能创建相应的分类页面。

另外本地图片的显示，你可以看下我给的示例，有些地没有引号，你加了引号也会出错。

欢迎你指出文档的不足，我也会更新文档，让它更好地配置。

2017年4月21日 下午6:20，"JackChius" <notifications@github.com>写道：

**Comment by zhangolve** [comment]
已更新文档。更加详细一点。

**Comment by JackChius** [comment]
嗯我看到了，目前这边还是无法显示相关页面，大都是Cannot GET /about之类的， 刚才也在网上搜了好多资料，主题的配置文件那里也关联了，现在有点懵逼的状态，博主方便加个微信/Q 打扰下吗囧
 758186328（q和微信好像都是这个）

**Comment by zhangolve** [comment]
你看我写的文档 about路径那一块。

2017年4月21日 下午11:02，"JackChius" <notifications@github.com>写道：

**Comment by zhangolve** [comment]
你那个微信搜索不到，我博客上有我微信号，你可以加我。

2017年4月21日 下午11:05，"张兴旺" <zhangolve@gmail.com>写道：
