### ISSUE TITLE
大佬 ，请问categories/大学/ 这种分类怎么配置呢

### ISSUE THREAD

**Issue by ChenYCL** [zhangolve/hexo-theme-olive#3]
分类了点击如何分类文章啊

**Comment by zhangolve** [comment]
只有你写了那个分类的文章，才应该给首页添加分类导航，不然这个分类下没有文章也没有意义。
举例来说，如果你写了一篇文章，分类写了大学，这个时候你在config配置文件里可以添加一个分类叫大学。但如果你添加一个分类叫高中，因为你没写这个分类的文章，就会出错了。

2018年1月25日 上午10:11，"ChenYCL" <notifications@github.com>写道：

**Comment by ChenYCL** [comment]
@zhangolve `
md我的头部如下
---
title: Hexo到Github样式不出来
date: 2017-09-04
categories: [Hexo,Github,前端]
tags:
    - Hexo
    - Github
    - 部署
keywords: github,hexo,style,404

##  在config中配置
# 显示左侧需要展示的目录，建议使用三到五个目录 ，如果不设置的话当然也没有问题

category: 
- 前端
- 大学
- 生活
---`

目前仍然不能分类到  source添加categorys文件夹无效

**Comment by ChenYCL** [comment]
解决了  categories: [Hexo,Github,前端] 只能单个添加分类啊😂   categories: xx 分类到

**Comment by zhangolve** [comment]
是的，像我这样。 tag可以放多个。

title: 多说死了，要换评论系统了
date: 2017-03-21  20:24:49 
categories: 网络
tags: [生活] 
description: 
copyright: false

解决了的话，就把这个issue关了吧。
