### ISSUE TITLE
大佬  部署上去 遇到一个问题 中文的分类无法找到

### ISSUE THREAD

**Issue by ChenYCL** [zhangolve/hexo-theme-olive#4]
看了你的博客 没有这个问题 ，这个你是怎么解决的啊
www.lgoweb.com 点前端 404

**Comment by zhangolve** [comment]
你看看你build完以后的public/categories 目录下有没有名字叫前端的文件夹。

2018年1月25日 下午4:39，"ChenYCL" <notifications@github.com>写道：

**Comment by ChenYCL** [comment]
好得 谢谢
